spring:
  data:
    rest:
      max-page-size: 300
      default-page-size: 150
      basePath: /data

springdoc:
  api-docs:
    path: /docs

server:
  port: 12345

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            repository:
              MongoRepository: DEBUG